"""Initial schema

Revision ID: 320070266d6c
Revises:
Create Date: 2026-06-01 04:15:08.055160

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '320070266d6c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('source_name', sa.String(length=50), nullable=False, comment='Source name'),
    sa.Column('provider_class', sa.String(length=200), nullable=False, comment='Provider class path'),
    sa.Column('api_key', sa.String(length=500), nullable=True, comment='API key'),
    sa.Column('rate_limit', sa.Integer(), nullable=True, comment='Rate limit (requests per second)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is active'),
    sa.Column('config_json', sa.JSON(), nullable=True, comment='Additional config as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_table('etf_info',
    sa.Column('code', sa.String(length=20), nullable=False, comment='ETF code'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='ETF name'),
    sa.Column('exchange', sa.String(length=10), nullable=True, comment='Exchange code'),
    sa.Column('market', sa.String(length=20), nullable=True, comment='Market (e.g. SH, SZ)'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Category'),
    sa.Column('sub_category', sa.String(length=50), nullable=True, comment='Sub-category'),
    sa.Column('manager', sa.String(length=100), nullable=True, comment='Fund manager'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='Currency'),
    sa.Column('is_qdii', sa.Boolean(), nullable=True, comment='Is QDII'),
    sa.Column('underlying_index', sa.String(length=200), nullable=True, comment='Underlying index name'),
    sa.Column('inception_date', sa.Date(), nullable=True, comment='Inception date'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_etf_info_category', 'etf_info', ['category'], unique=False)
    op.create_index('idx_etf_info_market', 'etf_info', ['market'], unique=False)
    op.create_index('idx_etf_info_status', 'etf_info', ['status'], unique=False)
    op.create_table('etf_pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Pool name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Pool description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('job_name', sa.String(length=100), nullable=False, comment='Job name'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='Data source'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending/running/success/failed'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='Start time'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='End time'),
    sa.Column('records_count', sa.Integer(), nullable=True, comment='Number of records processed'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='Error message'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='Additional metadata as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_etl_logs_job', 'etl_log', ['job_name'], unique=False)
    op.create_index('idx_etl_logs_status', 'etl_log', ['status'], unique=False)
    op.create_table('fx_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('from_currency', sa.String(length=10), nullable=False, comment='From currency'),
    sa.Column('to_currency', sa.String(length=10), nullable=False, comment='To currency'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='Trade date'),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Exchange rate'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='Data source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'trade_date', name='uq_fx_rate_currency_date')
    )
    op.create_index('idx_fx_rates_date', 'fx_rate', ['trade_date'], unique=False)
    op.create_table('strategy_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Strategy name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Strategy description'),
    sa.Column('strategy_type', sa.String(length=50), nullable=True, comment='Strategy type'),
    sa.Column('params', sa.JSON(), nullable=True, comment='Strategy parameters as JSON'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('strategy_id', sa.Integer(), nullable=False, comment='Strategy ID'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='Backtest start date'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Backtest end date'),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='Performance metrics as JSON'),
    sa.Column('trades', sa.JSON(), nullable=True, comment='Trade list as JSON'),
    sa.Column('config_snapshot', sa.JSON(), nullable=True, comment='Strategy config snapshot as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etf_daily_bar',
    sa.Column('etf_code', sa.String(length=20), nullable=False, comment='ETF code'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='Trade date'),
    sa.Column('open', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='Open price'),
    sa.Column('high', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='High price'),
    sa.Column('low', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='Low price'),
    sa.Column('close', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='Close price'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='Volume'),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Turnover amount'),
    sa.Column('pre_close', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='Previous close'),
    sa.Column('change_pct', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Change percentage'),
    sa.Column('turnover_rate', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Turnover rate'),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True, comment='Shares outstanding'),
    sa.Column('nav', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='Net asset value'),
    sa.Column('discount_rate', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Discount rate'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['etf_code'], ['etf_info.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('etf_code', 'trade_date')
    )
    op.create_table('etf_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('etf_code', sa.String(length=20), nullable=False, comment='ETF code'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='Trade date'),
    sa.Column('ma5', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='MA5'),
    sa.Column('ma10', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='MA10'),
    sa.Column('ma20', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='MA20'),
    sa.Column('ma60', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='MA60'),
    sa.Column('rsi14', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='RSI14'),
    sa.Column('macd_dif', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='MACD DIF'),
    sa.Column('macd_dea', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='MACD DEA'),
    sa.Column('macd_hist', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='MACD histogram'),
    sa.Column('volatility_20d', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='20-day volatility'),
    sa.Column('volatility_60d', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='60-day volatility'),
    sa.Column('max_drawdown_1y', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='1-year max drawdown'),
    sa.Column('sharpe_1y', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='1-year Sharpe ratio'),
    sa.Column('return_1w', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='1-week return'),
    sa.Column('return_1m', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='1-month return'),
    sa.Column('return_3m', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='3-month return'),
    sa.Column('return_6m', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='6-month return'),
    sa.Column('return_1y', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='1-year return'),
    sa.Column('atr14', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='ATR14'),
    sa.Column('bb_upper', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='Bollinger upper band'),
    sa.Column('bb_lower', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='Bollinger lower band'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['etf_code'], ['etf_info.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_code', 'trade_date', name='uq_indicator_code_date')
    )
    op.create_index('idx_indicators_code_date', 'etf_indicator', ['etf_code', 'trade_date'], unique=False)
    op.create_index('idx_indicators_date', 'etf_indicator', ['trade_date'], unique=False)
    op.create_table('pool_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pool_id', sa.Integer(), nullable=False, comment='Pool ID'),
    sa.Column('etf_code', sa.String(length=20), nullable=False, comment='ETF code'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Added time'),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True, comment='Removed time (NULL = currently in pool)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes'),
    sa.ForeignKeyConstraint(['etf_code'], ['etf_info.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['etf_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'etf_code', 'removed_at', name='uq_pool_member_pool_etf_removed')
    )
    op.create_index('idx_pool_members_etf', 'pool_member', ['etf_code'], unique=False, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_index('idx_pool_members_pool', 'pool_member', ['pool_id'], unique=False, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('signal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('strategy_id', sa.Integer(), nullable=False, comment='Strategy ID'),
    sa.Column('etf_code', sa.String(length=20), nullable=False, comment='ETF code'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='Trade date'),
    sa.Column('signal_type', sa.String(length=10), nullable=False, comment='Signal type: BUY/SELL/HOLD'),
    sa.Column('strength', sa.Integer(), nullable=True, comment='Signal strength'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='Additional metadata as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['etf_code'], ['etf_info.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal')
    op.drop_index('idx_pool_members_pool', table_name='pool_member', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index('idx_pool_members_etf', table_name='pool_member', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_table('pool_member')
    op.drop_index('idx_indicators_date', table_name='etf_indicator')
    op.drop_index('idx_indicators_code_date', table_name='etf_indicator')
    op.drop_table('etf_indicator')
    op.drop_table('etf_daily_bar')
    op.drop_table('backtest_result')
    op.drop_table('strategy_config')
    op.drop_index('idx_fx_rates_date', table_name='fx_rate')
    op.drop_table('fx_rate')
    op.drop_index('idx_etl_logs_status', table_name='etl_log')
    op.drop_index('idx_etl_logs_job', table_name='etl_log')
    op.drop_table('etl_log')
    op.drop_table('etf_pools')
    op.drop_index('idx_etf_info_status', table_name='etf_info')
    op.drop_index('idx_etf_info_market', table_name='etf_info')
    op.drop_index('idx_etf_info_category', table_name='etf_info')
    op.drop_table('etf_info')
    op.drop_table('data_source_config')
    # ### end Alembic commands ###
