"""add_crypto_trading_tables

Revision ID: 7d05c7c0d4f0
Revises: f6a7b8c9d0e1
Create Date: 2026-06-28 04:40:11.945634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d05c7c0d4f0'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_trade_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment config ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-readable label, e.g. 'Main Spot'"),
    sa.Column('api_key_encrypted', sa.String(length=512), nullable=True, comment='Fernet-encrypted Binance API key'),
    sa.Column('api_secret_encrypted', sa.String(length=512), nullable=True, comment='Fernet-encrypted Binance API secret'),
    sa.Column('is_testnet', sa.Boolean(), nullable=False, comment='Use testnet.binance.vision endpoints'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='Master switch for this config'),
    sa.Column('max_order_value', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Max USDT value per single order'),
    sa.Column('max_daily_loss', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Max daily realised loss before circuit-breaker'),
    sa.Column('max_daily_orders', sa.Integer(), nullable=True, comment='Max orders per calendar day'),
    sa.Column('allowed_symbols', sa.Text(), nullable=True, comment='JSON array of allowed instrument codes, empty = all'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Config creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last modification time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_trade_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment account ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable account label'),
    sa.Column('initial_balance', sa.DECIMAL(precision=18, scale=4), nullable=False, comment='Starting USDT balance'),
    sa.Column('cash', sa.DECIMAL(precision=18, scale=4), nullable=False, comment='Available USDT cash'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Quote currency'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Account creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last modification time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment rule ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable rule name'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='per_order | daily | market | duplicate'),
    sa.Column('param_key', sa.String(length=50), nullable=False, comment='e.g. max_order_value, max_daily_loss'),
    sa.Column('param_value', sa.String(length=100), nullable=False, comment='Threshold value as string'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this rule is enforced'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Rule creation time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='Auto-generated session title'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_trade_position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment position ID'),
    sa.Column('config_id', sa.Integer(), nullable=False, comment='Owning trade config'),
    sa.Column('instrument_code', sa.String(length=20), nullable=False, comment='Instrument code, e.g. BTC.US'),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Current position size'),
    sa.Column('avg_cost', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Volume-weighted average entry price'),
    sa.Column('current_price', sa.DECIMAL(precision=18, scale=8), nullable=True, comment='Last known price'),
    sa.Column('market_value', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Current market value in USDT'),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Unrealised PnL'),
    sa.Column('realized_pnl', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Realised PnL'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last sync time'),
    sa.ForeignKeyConstraint(['config_id'], ['live_trade_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'instrument_code', name='uq_ltp_config_code')
    )
    op.create_index(op.f('ix_live_trade_position_config_id'), 'live_trade_position', ['config_id'], unique=False)
    op.create_table('paper_trade_position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment position ID'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='Owning paper-trade account'),
    sa.Column('instrument_code', sa.String(length=20), nullable=False, comment='Instrument code, e.g. BTC.US'),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Current position size'),
    sa.Column('avg_cost', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Volume-weighted average entry price'),
    sa.Column('market_value', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Last-marked market value in USDT'),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Unrealised profit / loss'),
    sa.Column('realized_pnl', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='Realised profit / loss from closed lots'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last mark-to-market time'),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trade_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'instrument_code', name='uq_ptp_account_code')
    )
    op.create_index(op.f('ix_paper_trade_position_account_id'), 'paper_trade_position', ['account_id'], unique=False)
    op.create_table('research_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('instrument_code', sa.String(length=20), nullable=False, comment='Instrument code'),
    sa.Column('note_type', sa.String(length=50), nullable=False, comment='Note type: daily_summary, weekly_review, earnings_reaction, earnings_preview, manual'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full research note (markdown)'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='One-line summary'),
    sa.Column('sentiment', sa.String(length=20), nullable=True, comment='bullish, bearish, neutral'),
    sa.Column('confidence', sa.Integer(), nullable=True, comment='Confidence score 1-10'),
    sa.Column('source_data', sa.JSON(), nullable=True, comment='Snapshot of indicator/price data used'),
    sa.Column('generated_at', sa.DateTime(), nullable=True, comment='When this note was generated'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['instrument_code'], ['etf_info.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('instrument_code', sa.String(length=20), nullable=True, comment='Instrument code (NULL for market-wide)'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Source: finnhub_news, gdelt, earnings_call'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='Article/headline title'),
    sa.Column('content', sa.Text(), nullable=True, comment='Article/content text'),
    sa.Column('url', sa.String(length=1000), nullable=True, comment='Source URL'),
    sa.Column('sentiment_score', sa.DECIMAL(precision=5, scale=4), nullable=True, comment='Sentiment score: -1.0 (bearish) to 1.0 (bullish)'),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True, comment='positive, negative, neutral'),
    sa.Column('confidence', sa.DECIMAL(precision=5, scale=4), nullable=True, comment='Model confidence 0-1'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='Original publication time'),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Ingestion time'),
    sa.ForeignKeyConstraint(['instrument_code'], ['etf_info.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Session ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Role: user or assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content (markdown)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_trade_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment local order ID'),
    sa.Column('config_id', sa.Integer(), nullable=False, comment='Owning trade config'),
    sa.Column('order_id_from_exchange', sa.String(length=100), nullable=True, comment='Order ID returned by Binance'),
    sa.Column('instrument_code', sa.String(length=20), nullable=False, comment='Instrument code, e.g. BTC.US'),
    sa.Column('side', sa.String(length=10), nullable=False, comment='BUY | SELL'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='LIMIT | MARKET'),
    sa.Column('price', sa.DECIMAL(precision=18, scale=8), nullable=True, comment='Limit price (null for MARKET)'),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Base asset quantity'),
    sa.Column('filled_quantity', sa.DECIMAL(precision=18, scale=8), nullable=True, comment='Cumulative filled quantity'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | filled | partially_filled | cancelled | rejected'),
    sa.Column('reject_reason', sa.String(length=500), nullable=True, comment='Reason if status=rejected'),
    sa.Column('signal_id', sa.Integer(), nullable=True, comment='Signal that triggered this order (optional)'),
    sa.Column('raw_response', sa.Text(), nullable=True, comment='Raw JSON response from Binance for debugging'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Order creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last status update time'),
    sa.ForeignKeyConstraint(['config_id'], ['live_trade_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_trade_order_config_id'), 'live_trade_order', ['config_id'], unique=False)
    op.create_index(op.f('ix_live_trade_order_instrument_code'), 'live_trade_order', ['instrument_code'], unique=False)
    op.create_index('ix_lto_config_status', 'live_trade_order', ['config_id', 'status'], unique=False)
    op.create_index('ix_lto_instrument_time', 'live_trade_order', ['instrument_code', 'created_at'], unique=False)
    op.create_table('paper_trade_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment order ID'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='Owning paper-trade account'),
    sa.Column('instrument_code', sa.String(length=20), nullable=False, comment='Instrument code, e.g. BTC.US'),
    sa.Column('order_type', sa.String(length=10), nullable=False, comment='BUY | SELL'),
    sa.Column('price', sa.DECIMAL(precision=18, scale=8), nullable=True, comment='Execution price per unit'),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Order quantity in base asset'),
    sa.Column('filled_quantity', sa.DECIMAL(precision=18, scale=8), nullable=True, comment='Quantity that was filled'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | filled | cancelled | rejected'),
    sa.Column('reject_reason', sa.String(length=500), nullable=True, comment='Reason if status=rejected'),
    sa.Column('signal_id', sa.Integer(), nullable=True, comment='Signal that triggered this order (optional)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Order creation time'),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True, comment='Time the order was filled'),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trade_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trade_order_account_id'), 'paper_trade_order', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_trade_order_instrument_code'), 'paper_trade_order', ['instrument_code'], unique=False)
    op.create_index('ix_pto_account_status', 'paper_trade_order', ['account_id', 'status'], unique=False)
    op.create_index('ix_pto_instrument', 'paper_trade_order', ['instrument_code', 'created_at'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.alter_column('etf_info', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='Instrument code (e.g. 510050.SH, AAPL.US)',
               existing_comment='ETF code',
               existing_nullable=False)
    op.alter_column('etf_info', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               comment='Instrument name',
               existing_comment='ETF name',
               existing_nullable=False)
    op.alter_column('etf_info', 'exchange',
               existing_type=sa.VARCHAR(length=10),
               comment='Exchange code (SH, SZ, NYSE, NASDAQ, etc.)',
               existing_comment='Exchange code',
               existing_nullable=True)
    op.alter_column('etf_info', 'market',
               existing_type=sa.VARCHAR(length=20),
               comment='Market (A股, US, HK, JP)',
               existing_comment='Market (e.g. SH, SZ)',
               existing_nullable=True)
    op.alter_column('etf_info', 'currency',
               existing_type=sa.VARCHAR(length=10),
               comment='Currency (CNY, USD, HKD, JPY)',
               existing_comment='Currency',
               existing_nullable=True)
    op.alter_column('etf_info', 'fund_size',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Fund size / market cap in base currency',
               existing_comment='Fund size in CNY',
               existing_nullable=True)
    op.alter_column('etf_info', 'inception_date',
               existing_type=sa.DATE(),
               comment='Inception date / IPO date',
               existing_comment='Inception date',
               existing_nullable=True)
    op.alter_column('etf_info', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status (active, delisted, suspended)',
               existing_comment='Status',
               existing_nullable=True)
    op.alter_column('etf_info', 'instrument_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Instrument type: ETF or STOCK',
               existing_nullable=True,
               existing_server_default=sa.text("'ETF'::character varying"))
    op.alter_column('etf_info', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment='GICS sector',
               existing_nullable=True)
    op.alter_column('etf_info', 'industry',
               existing_type=sa.VARCHAR(length=100),
               comment='GICS industry',
               existing_nullable=True)
    op.alter_column('etf_info', 'market_cap',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Market capitalization (USD for US stocks)',
               existing_nullable=True)
    op.alter_column('etf_info', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment='Country of listing',
               existing_nullable=True)
    op.create_index('idx_etf_info_instrument_type', 'etf_info', ['instrument_type'], unique=False)
    op.alter_column('etf_scan_log', 'id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_scan_log', 'scan_date',
               existing_type=sa.DATE(),
               comment='Scan date',
               existing_nullable=False)
    op.alter_column('etf_scan_log', 'new_count',
               existing_type=sa.INTEGER(),
               comment='Number of new ETFs found',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('etf_scan_log', 'delisted_count',
               existing_type=sa.INTEGER(),
               comment='Number of delisted ETFs found',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('etf_scan_log', 'changed_count',
               existing_type=sa.INTEGER(),
               comment='Number of changed ETFs found',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('etf_scan_log', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Scan details as JSON',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('etf_scan_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status: success/failed',
               existing_nullable=True,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('etf_scan_log', 'error_msg',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('etf_scan_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_config', 'id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notification_config', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Config name',
               existing_nullable=False)
    op.alter_column('notification_config', 'channel_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               comment='Channel type: webhook/email',
               existing_nullable=False)
    op.alter_column('notification_config', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               comment='Channel-specific config',
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('notification_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Is active',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Update time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_log', 'id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notification_log', 'config_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Config ID')
    op.alter_column('notification_log', 'report_id',
               existing_type=sa.INTEGER(),
               comment='Report ID',
               existing_nullable=True)
    op.alter_column('notification_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status: pending/success/failed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('notification_log', 'error_msg',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='Error message',
               existing_nullable=True)
    op.alter_column('notification_log', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Send time',
               existing_nullable=True)
    op.alter_column('notification_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'notification_log', 'notification_config', ['config_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notification_log', 'report_metadata', ['report_id'], ['id'], ondelete='SET NULL')
    op.create_index('uq_pool_member_removed', 'pool_member', ['pool_id', 'etf_code', 'removed_at'], unique=True, postgresql_where=sa.text('removed_at IS NOT NULL'))
    op.alter_column('stock_balance_sheet', 'id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('stock_balance_sheet', 'stock_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Stock code',
               existing_nullable=False)
    op.alter_column('stock_balance_sheet', 'end_date',
               existing_type=sa.DATE(),
               comment='Report period end date',
               existing_nullable=False)
    op.alter_column('stock_balance_sheet', 'report_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Report type (Q1/Q2/Q3/Q4)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'ann_date',
               existing_type=sa.DATE(),
               comment='Announcement date',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_assets',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Total assets (万元)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_liab',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Total liabilities (万元)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_hldr_eqy_exc_min_int',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment="Shareholders' equity excl. minority interest (万元)",
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_cur_assets',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Total current assets (万元)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_cur_liab',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Total current liabilities (万元)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'current_ratio',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Current ratio',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'debt_to_assets',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Debt to assets ratio (%)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('stock_balance_sheet_stock_code_end_date_report_type_key'), 'stock_balance_sheet', type_='unique')
    op.create_unique_constraint('uq_stock_balance_sheet_code_period', 'stock_balance_sheet', ['stock_code', 'end_date', 'report_type'])
    op.alter_column('stock_fundamental', 'stock_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Stock code (e.g. 000001.SZ)',
               existing_nullable=False)
    op.alter_column('stock_fundamental', 'trade_date',
               existing_type=sa.DATE(),
               comment='Trade date',
               existing_nullable=False)
    op.alter_column('stock_fundamental', 'pe_ttm',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='PE (TTM)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'pb',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='PB (latest)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'total_mv',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Total market cap (万元 CNY)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'float_mv',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Free float market cap (万元 CNY)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'circ_mv',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Circulating market cap (万元 CNY)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'turnover_rate_f',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Free float turnover rate (%)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'volume_ratio',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Volume ratio',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'total_share',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Total shares (万股)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'float_share',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Free float shares (万股)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'free_share',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Unrestricted shares (万股)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_stock_fundamental_code_date', 'stock_fundamental', ['stock_code', 'trade_date'])
    op.alter_column('stock_income', 'id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('stock_income', 'stock_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Stock code',
               existing_nullable=False)
    op.alter_column('stock_income', 'end_date',
               existing_type=sa.DATE(),
               comment='Report period end date',
               existing_nullable=False)
    op.alter_column('stock_income', 'report_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Report type (Q1/Q2/Q3/Q4)',
               existing_nullable=True)
    op.alter_column('stock_income', 'ann_date',
               existing_type=sa.DATE(),
               comment='Announcement date',
               existing_nullable=True)
    op.alter_column('stock_income', 'total_revenue',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Total revenue (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'revenue_yoy',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Revenue YoY growth (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'operate_profit',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Operating profit (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'total_profit',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Total profit (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'n_income',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Net income (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'n_income_yoy',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Net income YoY growth (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'basic_eps',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='Basic EPS (元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'grossprofit_margin',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Gross profit margin (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'netprofit_margin',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Net profit margin (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'roe',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='ROE (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'roe_dt',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Deducted ROE (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'n_operate_cashflow',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Operating cash flow (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('stock_income_stock_code_end_date_report_type_key'), 'stock_income', type_='unique')
    op.create_unique_constraint('uq_stock_income_code_period', 'stock_income', ['stock_code', 'end_date', 'report_type'])
    op.create_foreign_key(None, 'user_favorite', 'users', ['username'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorite', type_='foreignkey')
    op.drop_constraint('uq_stock_income_code_period', 'stock_income', type_='unique')
    op.create_unique_constraint(op.f('stock_income_stock_code_end_date_report_type_key'), 'stock_income', ['stock_code', 'end_date', 'report_type'], postgresql_nulls_not_distinct=False)
    op.alter_column('stock_income', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_income', 'n_operate_cashflow',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Operating cash flow (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'roe_dt',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Deducted ROE (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'roe',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='ROE (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'netprofit_margin',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Net profit margin (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'grossprofit_margin',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Gross profit margin (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'basic_eps',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment=None,
               existing_comment='Basic EPS (元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'n_income_yoy',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Net income YoY growth (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'n_income',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Net income (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'total_profit',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Total profit (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'operate_profit',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Operating profit (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'revenue_yoy',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Revenue YoY growth (%)',
               existing_nullable=True)
    op.alter_column('stock_income', 'total_revenue',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Total revenue (万元)',
               existing_nullable=True)
    op.alter_column('stock_income', 'ann_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Announcement date',
               existing_nullable=True)
    op.alter_column('stock_income', 'report_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Report type (Q1/Q2/Q3/Q4)',
               existing_nullable=True)
    op.alter_column('stock_income', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Report period end date',
               existing_nullable=False)
    op.alter_column('stock_income', 'stock_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Stock code',
               existing_nullable=False)
    op.alter_column('stock_income', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_stock_fundamental_code_date', 'stock_fundamental', type_='unique')
    op.alter_column('stock_fundamental', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_fundamental', 'free_share',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Unrestricted shares (万股)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'float_share',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Free float shares (万股)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'total_share',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Total shares (万股)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'volume_ratio',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Volume ratio',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'turnover_rate_f',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Free float turnover rate (%)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'circ_mv',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Circulating market cap (万元 CNY)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'float_mv',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Free float market cap (万元 CNY)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'total_mv',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Total market cap (万元 CNY)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'pb',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment=None,
               existing_comment='PB (latest)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'pe_ttm',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment=None,
               existing_comment='PE (TTM)',
               existing_nullable=True)
    op.alter_column('stock_fundamental', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Trade date',
               existing_nullable=False)
    op.alter_column('stock_fundamental', 'stock_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Stock code (e.g. 000001.SZ)',
               existing_nullable=False)
    op.drop_constraint('uq_stock_balance_sheet_code_period', 'stock_balance_sheet', type_='unique')
    op.create_unique_constraint(op.f('stock_balance_sheet_stock_code_end_date_report_type_key'), 'stock_balance_sheet', ['stock_code', 'end_date', 'report_type'], postgresql_nulls_not_distinct=False)
    op.alter_column('stock_balance_sheet', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_balance_sheet', 'debt_to_assets',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Debt to assets ratio (%)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'current_ratio',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Current ratio',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_cur_liab',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Total current liabilities (万元)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_cur_assets',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Total current assets (万元)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_hldr_eqy_exc_min_int',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment="Shareholders' equity excl. minority interest (万元)",
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_liab',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Total liabilities (万元)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'total_assets',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Total assets (万元)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'ann_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Announcement date',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'report_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Report type (Q1/Q2/Q3/Q4)',
               existing_nullable=True)
    op.alter_column('stock_balance_sheet', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Report period end date',
               existing_nullable=False)
    op.alter_column('stock_balance_sheet', 'stock_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Stock code',
               existing_nullable=False)
    op.alter_column('stock_balance_sheet', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('uq_pool_member_removed', table_name='pool_member', postgresql_where=sa.text('removed_at IS NOT NULL'))
    op.drop_constraint(None, 'notification_log', type_='foreignkey')
    op.drop_constraint(None, 'notification_log', type_='foreignkey')
    op.alter_column('notification_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_log', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Send time',
               existing_nullable=True)
    op.alter_column('notification_log', 'error_msg',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Error message',
               existing_nullable=True)
    op.alter_column('notification_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Status: pending/success/failed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('notification_log', 'report_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Report ID',
               existing_nullable=True)
    op.alter_column('notification_log', 'config_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Config ID')
    op.alter_column('notification_log', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notification_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Update time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Is active',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_config', 'config_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment=None,
               existing_comment='Channel-specific config',
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('notification_config', 'channel_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Channel type: webhook/email',
               existing_nullable=False)
    op.alter_column('notification_config', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Config name',
               existing_nullable=False)
    op.alter_column('notification_config', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_scan_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_scan_log', 'error_msg',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('etf_scan_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Status: success/failed',
               existing_nullable=True,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('etf_scan_log', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Scan details as JSON',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('etf_scan_log', 'changed_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of changed ETFs found',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('etf_scan_log', 'delisted_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of delisted ETFs found',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('etf_scan_log', 'new_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of new ETFs found',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('etf_scan_log', 'scan_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Scan date',
               existing_nullable=False)
    op.alter_column('etf_scan_log', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_etf_info_instrument_type', table_name='etf_info')
    op.alter_column('etf_info', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Country of listing',
               existing_nullable=True)
    op.alter_column('etf_info', 'market_cap',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Market capitalization (USD for US stocks)',
               existing_nullable=True)
    op.alter_column('etf_info', 'industry',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='GICS industry',
               existing_nullable=True)
    op.alter_column('etf_info', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='GICS sector',
               existing_nullable=True)
    op.alter_column('etf_info', 'instrument_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Instrument type: ETF or STOCK',
               existing_nullable=True,
               existing_server_default=sa.text("'ETF'::character varying"))
    op.alter_column('etf_info', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status',
               existing_comment='Status (active, delisted, suspended)',
               existing_nullable=True)
    op.alter_column('etf_info', 'inception_date',
               existing_type=sa.DATE(),
               comment='Inception date',
               existing_comment='Inception date / IPO date',
               existing_nullable=True)
    op.alter_column('etf_info', 'fund_size',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Fund size in CNY',
               existing_comment='Fund size / market cap in base currency',
               existing_nullable=True)
    op.alter_column('etf_info', 'currency',
               existing_type=sa.VARCHAR(length=10),
               comment='Currency',
               existing_comment='Currency (CNY, USD, HKD, JPY)',
               existing_nullable=True)
    op.alter_column('etf_info', 'market',
               existing_type=sa.VARCHAR(length=20),
               comment='Market (e.g. SH, SZ)',
               existing_comment='Market (A股, US, HK, JP)',
               existing_nullable=True)
    op.alter_column('etf_info', 'exchange',
               existing_type=sa.VARCHAR(length=10),
               comment='Exchange code',
               existing_comment='Exchange code (SH, SZ, NYSE, NASDAQ, etc.)',
               existing_nullable=True)
    op.alter_column('etf_info', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               comment='ETF name',
               existing_comment='Instrument name',
               existing_nullable=False)
    op.alter_column('etf_info', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='ETF code',
               existing_comment='Instrument code (e.g. 510050.SH, AAPL.US)',
               existing_nullable=False)
    op.create_table('user_devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=20), server_default=sa.text("'ios'::character varying"), autoincrement=False, nullable=False),
    sa.Column('push_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_devices_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_devices_pkey'))
    )
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('token_hash', name=op.f('refresh_tokens_token_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_index('ix_pto_instrument', table_name='paper_trade_order')
    op.drop_index('ix_pto_account_status', table_name='paper_trade_order')
    op.drop_index(op.f('ix_paper_trade_order_instrument_code'), table_name='paper_trade_order')
    op.drop_index(op.f('ix_paper_trade_order_account_id'), table_name='paper_trade_order')
    op.drop_table('paper_trade_order')
    op.drop_index('ix_lto_instrument_time', table_name='live_trade_order')
    op.drop_index('ix_lto_config_status', table_name='live_trade_order')
    op.drop_index(op.f('ix_live_trade_order_instrument_code'), table_name='live_trade_order')
    op.drop_index(op.f('ix_live_trade_order_config_id'), table_name='live_trade_order')
    op.drop_table('live_trade_order')
    op.drop_table('ai_chat_message')
    op.drop_table('sentiment_data')
    op.drop_table('research_note')
    op.drop_index(op.f('ix_paper_trade_position_account_id'), table_name='paper_trade_position')
    op.drop_table('paper_trade_position')
    op.drop_index(op.f('ix_live_trade_position_config_id'), table_name='live_trade_position')
    op.drop_table('live_trade_position')
    op.drop_table('ai_chat_session')
    op.drop_table('risk_rule')
    op.drop_table('paper_trade_account')
    op.drop_table('live_trade_config')
    # ### end Alembic commands ###
