"""add etf_scan_log table

Revision ID: b1d9c108e92a
Revises: 5653af0ec7a7
Create Date: 2026-06-02 02:43:02.110976

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b1d9c108e92a'
down_revision: str | Sequence[str] | None = '5653af0ec7a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
